version: '3.8'

services:
  # Веб API приложение
  webapptrain:
    image: ${DOCKER_REGISTRY-}webapptrain
    container_name: webapptrain
    build:
      context: .
      dockerfile: WebAppTrain/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network

  # База данных PostgreSQL
  database:
    image: postgres:13
    container_name: database
    environment:
      - POSTGRES_DB=TestDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass1!2@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP порт
      - "15672:15672"  # Management UI порт
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

# Сервис валидации
  validationservice:
    image: ${DOCKER_REGISTRY-}validationservice
    container_name: validationservice
    build:
      context: .
      dockerfile: IntegrationServices/ValidationService/Dockerfile
    networks:
      - app-network

# Объемы данных
volumes:
  postgres_data:

# Сети
networks:
  app-network:
    driver: bridge