services:
  webapptrain:
    image: ${DOCKER_REGISTRY-}webapptrain
    container_name: webapptrain
    build:
      context: .
      dockerfile: WebAppTrain/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

# database postgres
  database:
    image: postgres:13
    container_name: database
    environment:
      - POSTGRES_DB=TestDatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass1!2@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

#RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP порт
      - "15672:15672"  # Management UI порт
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest