version: '3.8'

services:
  webapi:
    image: webapi-image
    build:
      context: ../WebAppTrain
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=TestDatabase;Username=postgres;Password=Pass1!2@;Port=5432
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - rabbitmq
      - postgres

  validation-service:
    image: validation-service-image
    build:
      context: ../IntegrationServices/ValidationService
    environment:
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: TestDatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass1!2@
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: